openapi: "3.0.1"
info:
  title: "Product Service"
  description: "This service serves products."
  version: "0.0.1"
servers:
  - url: "https://7zu57pqm72.execute-api.eu-west-1.amazonaws.com/{basePath}"
    variables:
      basePath:
        default: "prod"
paths:
  /products:
    get:
      responses:
        "200":
          description: "List of available products"
          content:
            application-json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
  /products/{productId}:
    get:
      parameters:
        - name: "productId"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "Single produt by id"
          content:
            application-json:
              schema:
                $ref: "#/components/schemas/Product"
        "404":
          description: "Product not found"

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        price:
          type: number
        description:
          type: string
        count:
          type: integer
      description: product description
